apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-l0xf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bned-tenant/rhtap-demo-app/hacbs-test-project-l0xf@sha256:676afbebb5c1a215522fd774e9f323965de4c7a12b4e96cd4d6e0d005678f395
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
