apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-l0xf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-l0xf
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-l0xf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-l0xf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-l0xf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bned-tenant/rhtap-demo-app/hacbs-test-project-l0xf@sha256:660a067c54e03fcb645e99fb603421743ab4a8d46acef71cad3677220ddbae40
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
